#!/bin/sh
### BEGIN INIT INFO
# Provides:          aafirstboot
# Required-Start:    $remote_fs $all
# Required-Stop:
# Default-Start:     2 3 4 5 S
# Default-Stop:
# Short-Description: First boot system setup
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

if [ -e /proc/fs/ext4/mmcblk0p2 ]; then
    MMCBLK=mmcblk0
elif [ -e /proc/fs/ext4/mmcblk1p2 ]; then
    MMCBLK=mmcblk1
else
    exit 1
fi

if [ -f /.first_boot ]; then
	mkdir -p /media/boot
	# ok, its the very first boot, we need to resize the disk.
	p2_start=`fdisk -l /dev/${MMCBLK} | grep ${MMCBLK}p2 | awk '{print $4}'`
	p2_finish=`fdisk -l /dev/${MMCBLK} | grep sectors | awk '{printf $7}'`

	fdisk -u /dev/${MMCBLK} <<EOF
p
d
2
n
p
2
$p2_start
$(($p2_finish-1))
p
w
EOF
	rm -fr /.first_boot
	sync
	reboot
else
	resize2fs /dev/${MMCBLK}p2 && rm -fr /aafirstboot
fi
